### PR TITLE
Feature/add serial number to cce setup

### PR DESCRIPTION
**Pull request by musamusa**

### CODE REVIEW

**Comment by musamusa** [comment]
@jofomah, I just updated the PR

**Comment by jofomah** [comment]
@musamusa cool, just checked it out and i noticed the following:
1. When i click on "Add button" i can add an empty CCE Serial number to the list.
2. i can only add two Serial Numbers, if i click Add after that nothing happens.
3. If i add a CCE serial number, moves to another, to edit or update requires to unselect (thought we agreed to have a button)
4. Add and Remove buttons don't work most times, usually stop working after you clicked twice
5. I can't save app config.

**Comment by musamusa** [comment]
@jofomah, fixed, awaiting review

**Comment by musamusa** [comment]
@jofomah, I just updated this and tested with first setup, kindly review and let me know if I'm missing anything

**Comment by jofomah** [comment]
@musamusa will review later, maybe when am back in Kano. thanks

**Comment by janetbutts** [comment]
completed, but cannot be merged. will go in on next mini-release.

**Comment by janetbutts** [comment]
@jofomah , know this can't be merged now, but is it ready to go other than that? thought i remember you saying it was, but look at the history, it doesn't appear ready.

**Comment by janetbutts** [comment]
@jofomah , are we just waiting to merge  or are there other outstanding issues?

**Comment by jofomah** [comment]
merged `upstream/develop` and noticed the following:
- multiple clicks on "Add" button creates multiple empty rows. To reproduce:
  1. Select CCE Profile
  2. Each time you click on the the expand toggle button, it adds new empty row.
     cce setup bug
- when i merged latest upstream, i can't add CCE serial number, when i click on drop down toggle button, nothing happens both at Setup and Edit App Config section.
- When i click on drop down toggle button without selecting product profile first, nothing happens, thought we agreed to show an information alert that tells the user to select CCE Profile first before adding CCE serial number information.

**Comment by janetbutts** [comment]
hey @musumusa, please address.

**Pull request closed without merging**
