### PR TITLE
Offline analytics

### PR DESCRIPTION
**Pull request by tlvince**
:tada:

### CODE REVIEW

**Comment by tlvince** [comment]
@thanasio, I've rebased your earlier work in #477. However, it currently throws:

``` js
TypeError: undefined is not a function
    at appView (chrome-extension://fopkonkhmleflobaijjojmnfmmaoiiin/scripts/services/tracking-factory.js:86:29)
```

This could be because if Google Analytics fails to load (for whatever reason), those properties are unset. You could mock them like in the earlier [trackingService](https://github.com/eHealthAfrica/LMIS-Chrome/blob/1affda7f2830c75aa8597a7a3eaf9fd239f6cc79/app/scripts/services/tracking-service.js#L5-L10).

A few other things:
- Please could you add `**.orig` to your global Git ignore to prevent transient diff files from being committed
- A few commits were committed un merged (they still had diff markers (`=======` etc.))
- Generalising the logic in `trackingFactory` into a helper (DRY)

**Comment by tlvince** [comment]
Also, it's worth keeping an eye out for merges into `develop` (e.g. in the Flowdock stream) to prevent your work from falling behind `develop`.

My workflow is:
1. Make sure local develop is up to date (`git pull origin develop`)
2. Create topic branch
3. Code
4. If a pull request has been merged, pull down develop, rebase topic branch and resolve any conflicts then and there:

``` js
git checkout develop
git pull origin develop
git checkout topic
git rebase develop
```

Repeat steps 3-4 until topic is ready, do a final pull/rebase and submit pull request.

You don't have to follow my workflow, but I suggest at least rebasing more often to prevent these tangled pull requests. Since we don't have a fixed 'merge in day' and time moves quickly on this project (there have been 3 merges while writing this(!)), its worth the extra effort and saves time in the long run.

**Comment by thanasio** [comment]
Hey Tom, if you want i can take a look on the rebased code at some point, as i cannot remember exceptions thrown on my end. Maybe something changed during consequent rebases! PM me if you need any help in regards to get this working!

**Comment by tlvince** [comment]
@thanasio, yeah, you're right; I tracked the exceptions down to my machine blocking GA at the OS level (in `/etc/hosts`). Worked around by mocking the GA methods that we use if GA is unset.

**Comment by thanasio** [comment]
Ok, let me know if you have more probs. It should be working without any errors, as i give them a good test inspecting all outputs with google dev tools. Make sure you re-adjust the limits for the priority queue (config.json). As they stand now they are quite small and overflow to the lost_records tables over 9-10 entries.
Thanks!
T

**Comment by thanasio** [comment]
Hehe, just realised, step number 3 of your recommendations was missing, hence my rebasing tragedies...lol...:)...will definately follow this now!

**Comment by tlvince** [comment]
:smile:

**Pull request merged**
