### PR TITLE
Feature/create immunization summary sheet

### PR DESCRIPTION
**Pull request by musamusa**

### CODE REVIEW

**Comment by musamusa** [comment]
Feedback for MMorland, prod owner for updates:
*Group Vaccine in a grid format - product against vaccination stages
*Add location information to summary data every time its updated
*Create a summary breakdown of data submitted
*Add a simple chart of how many times a session is completed per week (not required)

**Comment by janetbutts** [comment]
@musamusa , let's see if M Moreland can give us some feedback after vacation on Monday. Thanks.

**Comment by janetbutts** [comment]
@musamusa , i know this is on hold for the moment until UX review, but please handle the errors above.

**Comment by janetbutts** [comment]
@musamusa , what is the status?

**Pull request closed without merging**
