### PR TITLE
selectable app-config rows 

### PR DESCRIPTION
**Pull request by musamusa**

### CODE REVIEW

**Comment by tlvince** [comment]
This won't work within the padded area of the row. It might also be nice to display `cursor: hand`.

**Comment by musamusa** [comment]
I noticed that, i could have taken that out by just overwriting the padding for the outer div, the effect is hardly noticeable in a mobile device. I also thought of adding the pointer class, also not useful in a mobile device.

**Comment by musamusa** [comment]
@tlvince, take a look at the update

**Comment by tlvince** [comment]
:thumbsup:

We should support desktop just as much as mobile.

**Pull request merged**
