### PR TITLE
Feature/utilization module (Complete)

### PR DESCRIPTION
**Pull request by musamusa**

### CODE REVIEW

**Comment by jofomah** [comment]
is this work in progress or complete?

**Comment by musamusa** [comment]
work in progress

**Comment by janetbutts** [comment]
@musamusa can you provide a status? thanks.

**Comment by musamusa** [comment]
@jofomah, just completed this and awaiting review, cc @janetbutts

**Comment by janetbutts** [comment]
@jofomah , pleave review and provide feeback to @musamusa . Thanks

**Comment by jofomah** [comment]
@janetbutts ok will do that currently preparing DD Deployment Steps documentation for Norbert, thanks

**Comment by jofomah** [comment]
also lets try and add test for new Services and Controller functions, step by step we can improve LoMIS code base and test coverage. Thanks.

**Comment by janetbutts** [comment]
@musamusa , please let @jofomah know when you are ready for review again.

**Comment by musamusa** [comment]
@jofomah, PR updated and waiting for review cc @janetbutts

**Comment by janetbutts** [comment]
@jofomah , can you review?

**Comment by jofomah** [comment]
Some of the comment have not been resolved e.g
`['balance', 'received', 'used', 'endingBalance', 'returned']` 

@musamusa this is a magic array, if it is quantity types, let's assigned it to a variable or constant with a descriptive name. Thanks.

**Comment by janetbutts** [comment]
@musamusa, please review and correct any issues.

**Comment by janetbutts** [comment]
@musamusa, please review.

**Comment by janetbutts** [comment]
@musamusa , since we moved to the move repo, can this be closed?

**Pull request closed without merging**
